CREATE TABLE policies (
    rule_id UUID PRIMARY KEY,
    action VARCHAR(255),
    additional_properties JSONB,
    bi_directional INT,
    comments TEXT,
    device_rule_num INT,
    dst JSONB,
    dst_negate INT,
    enable VARCHAR(50),
    expanded_action VARCHAR(255),
    global_nat VARCHAR(255),
    line_number INT,
    load_balancer_rule BOOLEAN,
    log INT,
    map_source_to_interface BOOLEAN,
    map_source_to_same_address BOOLEAN,
    nat VARCHAR(255),
    object_nat_destination BOOLEAN,
    object_nat_source BOOLEAN,
    rule_grp VARCHAR(255),
    rule_name VARCHAR(255),
    rule_num INT,
    service JSONB,
    service_negate INT,
    src JSONB,
    src_negate INT,
    target JSONB,
    use_nat_pools BOOLEAN
);